### PR TITLE
[#2251] Updating package to 3.2

### PR DESCRIPTION
**Pull request by ErhanCitil**
Updating the Python package to the Django 3.2 version

### CODE REVIEW

**Comment by alextreme** [comment]
tox.ini has been updated, tests are currently failing

**Review by alextreme — CHANGES_REQUESTED** [review]
tests

**Comment by ErhanCitil** [comment]
@alextreme deze pull request kan nagekeken worden zodat we hem kunnen gebruiken in Jenkins

**Comment by alextreme** [comment]
@ErhanCitil zoals besproken, je mag nog even kijken naar de tests:

============================================================================= ERRORS =============================================================================
_____________________________________________________________ ERROR collecting tests/test_models.py ______________________________________________________________
ImportError while importing test module '/home/alex/maykin/djangocms-export-page/tests/test_models.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_models.py:1: in <module>
    from test.blog.tests.factories import BlogFactory
E   ModuleNotFoundError: No module named 'test.blog'
______________________________________________________________ ERROR collecting tests/test_pages.py ______________________________________________________________
ImportError while importing test module '/home/alex/maykin/djangocms-export-page/tests/test_pages.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_pages.py:1: in <module>
    from test.plugins.tests.factories import PageFactory
E   ModuleNotFoundError: No module named 'test.plugins'
______________________________________________________________ ERROR collecting tests/test_utils.py ______________________________________________________________
ImportError while importing test module '/home/alex/maykin/djangocms-export-page/tests/test_utils.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_utils.py:3: in <module>
    from ..utils import clean_value
E   ImportError: attempted relative import with no known parent package

**Review by alextreme — CHANGES_REQUESTED** [review]
3 falende tests

**Comment by alextreme** [comment]
@ErhanCitil stapje verder, nog wel 2 falende tests:

py39-django32 run-test: commands[0] | py.test tests --junitxml=reports/junit.xml --cov --cov-report xml:reports/coverage-py39-django32.xml
=============================================================================== test session starts ================================================================================
platform linux -- Python 3.9.2, pytest-7.2.2, pluggy-1.0.0
cachedir: .tox/py39-django32/.pytest_cache
rootdir: /home/alex/maykin/djangocms-export-page, configfile: setup.cfg
plugins: cov-4.0.0, django-4.5.2
collected 5 items / 2 errors                                                                                                                                                       

====================================================================================== ERRORS ======================================================================================
______________________________________________________________________ ERROR collecting tests/test_models.py _______________________________________________________________________
tests/test_models.py:3: in <module>
    from djangocms_export_page.export.common import PageExport
.tox/py39-django32/lib/python3.9/site-packages/djangocms_export_page/export/__init__.py:1: in <module>
    from .common import *  # noqa
.tox/py39-django32/lib/python3.9/site-packages/djangocms_export_page/export/common.py:6: in <module>
    from cms.models import CMSPlugin, Placeholder, StaticPlaceholder
.tox/py39-django32/lib/python3.9/site-packages/cms/models/__init__.py:1: in <module>
    from .settingmodels import *  # nopyflakes
.tox/py39-django32/lib/python3.9/site-packages/cms/models/settingmodels.py:7: in <module>
    class UserSettings(models.Model):
.tox/py39-django32/lib/python3.9/site-packages/cms/models/settingmodels.py:9: in UserSettings
    settings.AUTH_USER_MODEL,
.tox/py39-django32/lib/python3.9/site-packages/django/conf/__init__.py:82: in __getattr__
    self._setup(name)
.tox/py39-django32/lib/python3.9/site-packages/django/conf/__init__.py:63: in _setup
    raise ImproperlyConfigured(
E   django.core.exceptions.ImproperlyConfigured: Requested setting AUTH_USER_MODEL, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
_______________________________________________________________________ ERROR collecting tests/test_pages.py _______________________________________________________________________
tests/test_pages.py:3: in <module>
    from cms.api import add_plugin, create_page
.tox/py39-django32/lib/python3.9/site-packages/cms/api.py:11: in <module>
    from django.contrib.sites.models import Site
.tox/py39-django32/lib/python3.9/site-packages/django/contrib/sites/models.py:78: in <module>
    class Site(models.Model):
.tox/py39-django32/lib/python3.9/site-packages/django/db/models/base.py:108: in __new__
    app_config = apps.get_containing_app_config(module)
.tox/py39-django32/lib/python3.9/site-packages/django/apps/registry.py:253: in get_containing_app_config
    self.check_apps_ready()
.tox/py39-django32/lib/python3.9/site-packages/django/apps/registry.py:135: in check_apps_ready
    settings.INSTALLED_APPS
.tox/py39-django32/lib/python3.9/site-packages/django/conf/__init__.py:82: in __getattr__
    self._setup(name)
.tox/py39-django32/lib/python3.9/site-packages/django/conf/__init__.py:63: in _setup
    raise ImproperlyConfigured(
E   django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
-------------------------------------------------- generated xml file: /home/alex/maykin/djangocms-export-page/reports/junit.xml ---------------------------------------------------

----------- coverage: platform linux, python 3.9.2-final-0 -----------
Coverage XML written to file reports/coverage-py39-django32.xml

**Comment by Coperh** [comment]
The tests should now pass if installed correctly in the annefrank site, which seems like the project used to test this.

**BlogFactory** and **BodyTextPlugin** are implement there>

It needed a test template with the _placeholder_  tag already in it. Adding it in code did not work.

**Review by alextreme — APPROVED** [review]

**Pull request merged**
